In [6]:
import numpy as np
import pandas as pd

In [7]:
import matplotlib.pyplot as plt
import seaborn as s

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [13]:
test_df=pd.read_csv("C:\\Users\\User\\Downloads\\test.csv")
test_df

row_id           StudyInstanceUID prediction_type
0  1.2.826.0.1.3680043.10197_C1  1.2.826.0.1.3680043.10197              C1
1  1.2.826.0.1.3680043.10454_C1  1.2.826.0.1.3680043.10454              C1
2  1.2.826.0.1.3680043.10690_C1  1.2.826.0.1.3680043.10690              C1

In [14]:
train_df=pd.read_csv("C:\\Users\\User\\Downloads\\train.csv")
train_df

StudyInstanceUID  patient_overall  C1  C2  C3  C4  C5  C6  C7
0      1.2.826.0.1.3680043.6200                1   1   1   0   0   0   0   0
1     1.2.826.0.1.3680043.27262                1   0   1   0   0   0   0   0
2     1.2.826.0.1.3680043.21561                1   0   1   0   0   0   0   0
3     1.2.826.0.1.3680043.12351                0   0   0   0   0   0   0   0
4      1.2.826.0.1.3680043.1363                1   0   0   0   0   1   0   0
...                         ...              ...  ..  ..  ..  ..  ..  ..  ..
2014  1.2.826.0.1.3680043.21684                1   0   1   0   0   0   1   1
2015   1.2.826.0.1.3680043.4786                1   0   0   0   0   0   0   1
2016  1.2.826.0.1.3680043.14341                0   0   0   0   0   0   0   0
2017  1.2.826.0.1.3680043.12053                0   0   0   0   0   0   0   0
2018  1.2.826.0.1.3680043.18786                1   0   0   0   0   0   0   1

[2019 rows x 9 columns]

In [16]:
train_df.shape

(2019, 9)

In [17]:
test_df.shape

(3, 3)

In [18]:
train_df.head(15)

StudyInstanceUID  patient_overall  C1  C2  C3  C4  C5  C6  C7
0    1.2.826.0.1.3680043.6200                1   1   1   0   0   0   0   0
1   1.2.826.0.1.3680043.27262                1   0   1   0   0   0   0   0
2   1.2.826.0.1.3680043.21561                1   0   1   0   0   0   0   0
3   1.2.826.0.1.3680043.12351                0   0   0   0   0   0   0   0
4    1.2.826.0.1.3680043.1363                1   0   0   0   0   1   0   0
5    1.2.826.0.1.3680043.4859                1   0   0   0   0   0   1   0
6   1.2.826.0.1.3680043.18659                1   0   0   0   1   0   0   1
7   1.2.826.0.1.3680043.17364                0   0   0   0   0   0   0   0
8     1.2.826.0.1.3680043.849                0   0   0   0   0   0   0   0
9   1.2.826.0.1.3680043.24045                1   0   0   0   0   0   0   1
10   1.2.826.0.1.3680043.4744                1   0   0   0   1   1   0   0
11  1.2.826.0.1.3680043.15773                1   1   1   0   0   0   0   1
12  1.2.826.0.1.3680043.24946                0   0   0   0   0   0   0   0
13   1.2.826.0.1.3680043.9290                0   0   0   0   0   0   0   0
14   1.2.826.0.1.3680043.5482                1   1   0   0   0   0   0   0

In [19]:
test_df.head()

row_id           StudyInstanceUID prediction_type
0  1.2.826.0.1.3680043.10197_C1  1.2.826.0.1.3680043.10197              C1
1  1.2.826.0.1.3680043.10454_C1  1.2.826.0.1.3680043.10454              C1
2  1.2.826.0.1.3680043.10690_C1  1.2.826.0.1.3680043.10690              C1

In [20]:
x=train_df[['C1','C2','C3','C4','C5','C6','C7']].values
x

array([[1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [21]:
y=train_df[['patient_overall']].values
y

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]], dtype=int64)

In [24]:
model = LogisticRegression()
model.fit(x, y)
y_pred = model.predict(x)

print("accuracy:", accuracy_score(y, y_pred))
print("precision:", precision_score(y, y_pred))
print("recall:", recall_score(y, y_pred))
print("f1 score:", f1_score(y, y_pred))

accuracy: 1.0
precision: 1.0
recall: 1.0
f1 score: 1.0


C:\Users\User\anaconda\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

print("whole dataset:", x.shape, y.shape)
print("training set:", x_train.shape, y_train.shape)
print("test set:", x_test.shape, y_test.shape)

whole dataset: (2019, 7) (2019, 1)
training set: (1514, 7) (1514, 1)
test set: (505, 7) (505, 1)


In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
print(confusion_matrix(y, y_pred))

[[1058    0]
 [   0  961]]
